
export const FREE_READINGS = 3;

export const SUBSCRIPTION_TIERS = {
  standard: {
    name: 'Standard',
    price: '$4.99/mo',
    monthlyReads: 20,
    features: [
      '20 palm readings per month',
      'Full palm analysis',
      'Heart, Head, Life & Fate lines',
      'Special marks interpretation',
      'Reading history',
    ],
  },
  premium: {
    name: 'Premium',
    price: '$14.99/mo',
    monthlyReads: 100,
    features: [
      '100 palm readings per month',
      'Advanced palm analysis',
      'All Standard features',
      'Deeper insights & guidance',
      '3 personalized prompts',
      '3 spiritual practices',
    ],
  },
};

// RevenueCat entitlement identifiers -> app tiers.
// Configure entitlements with these exact IDs in the RevenueCat dashboard.
export const ENTITLEMENTS = {
  standard: 'standard',
  premium: 'premium',
} as const;

export const SUPPORT_EMAIL = 'support@destinylines.app';

// Hosted from the docs/ folder via GitHub Pages (repo: meeglosh/destiny-lines-app).
// Enable Pages (Settings -> Pages -> main branch, /docs folder) before submission.
export const LEGAL_URLS = {
  privacy: 'https://meeglosh.github.io/destiny-lines-app/privacy.html',
  terms: 'https://meeglosh.github.io/destiny-lines-app/terms.html',
};

export const DISCLAIMER_TEXT = `
Destiny Lines is for entertainment purposes only.
Palm readings are not medical, legal, or financial advice.
Results are generated by AI and should not be used for making important life decisions.
`;

export const TOS_TEXT = `
By using Destiny Lines, you agree to:
- Use the app for entertainment only
- Not rely on readings for medical, legal, or financial decisions
- Be at least 16 years of age
- Allow us to process your palm images (analyzed in memory, never stored)
- Our privacy policy and terms of service
`;
