
export const SUBSCRIPTION_TIERS = {
  standard: {
    name: 'Standard',
    price: '$4.99/mo',
    monthlyReads: 20,
    dailyLimit: 5,
    features: [
      '20 palm readings per month',
      'Up to 5 readings per day',
      'Basic palm analysis',
      'Heart, Head, Life & Fate lines',
      'Special marks interpretation',
    ],
  },
  premium: {
    name: 'Premium',
    price: '$14.99/mo',
    monthlyReads: 100,
    dailyLimit: 15,
    features: [
      '100 palm readings per month',
      'Up to 15 readings per day',
      'Advanced palm analysis',
      'All basic features',
      'Deeper insights & guidance',
      '3 personalized prompts',
      '3 spiritual practices',
    ],
  },
};

export const DISCLAIMER_TEXT = `
Destiny Lines is for entertainment purposes only. 
Palm readings are not medical, legal, or financial advice. 
Results are generated by AI and should not be used for making important life decisions.
`;

export const TOS_TEXT = `
By using Destiny Lines, you agree to:
- Use the app for entertainment only
- Not rely on readings for medical, legal, or financial decisions
- Be at least 16 years of age
- Allow us to process your palm images temporarily (deleted within 10 minutes)
- Our privacy policy and data handling practices
`;
